; Rename this file to config.ini and fill in the values below.

[Twitch]
access_token = YOUR_NEW_ACCESS_TOKEN
client_id = YOUR_NEW_CLIENT_ID

; If you already have the above two, you can get broadcaster_id by running get_user_id.py
broadcaster_id = YOUR_NEW_BROADCASTER_ID



[TSH]
; The paths are used to grab information stored by TSH, to be used in the Twitch predictions.
; The paths are relative to the location of this file.
p1_file = ../../out/score/1/team/1/player/1/name.txt
p2_file = ../../out/score/1/team/2/player/1/name.txt
round_name = ../../out/score/1/match.txt
p1_score = ../../out/score/1/team/1/score.txt
p2_score = ../../out/score/1/team/2/score.txt

; The time in seconds until the prediction closes.
; I have it at 10 minutes to capture two mid-length rounds
prediction_time = 600

